wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.1
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1704580094.965301
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.16.1
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
