wandb_version: 1

learning:
  desc: null
  value: marketing-analytics
task:
  desc: null
  value: classification
env:
  desc: null
  value: local
datasource:
  desc: null
  value: kaggle
model:
  desc: null
  value: xgboost
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.16.1
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1704581661.987012
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.16.1
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
